#!/bin/bash

NAS_PROG=${NAS_PROG:-/mnt/auto/dns-323/Nas_Prog}

fatal()
{
    echo "Error: $*"
    exit 1
}

list()
{
    echo "Name                 Version   Description"
    echo "================================================================================"
    infos=`ls $NAS_PROG/*/info $NAS_PROG/shared/*/info 2> /dev/null`
    for info in $infos ; do
	. $info
	printf "%-20s %-9s %s\n" "$NAME" "$VERSION" "$DESCRIPTION"
    done | sort
}

build-pkg()
{
    . packages/$1/info || fatal "Failed to find info file of package $1"

    echo "Building $NAME"

    xform=${NAME/shared-/shared/}
    tar -C packages --xform s,$NAME,$xform, -czf packages/$NAME-$VERSION.tgz \
	$NAME
}

build-all()
{
    for dir in packages/* ; do
	if [ -d $dir ] ; then
	    build-pkg ${dir##packages/}
	fi
    done
}

build-clean()
{
    rm packages/*.tgz 2> /dev/null
    find packages \( -name '*~' \) -type f -print | xargs rm -f
}

case "$1" in
    list)
	list
	;;
    build-pkg)
	build-pkg $2
	;;
    build-all)
	build-all
	;;
    build-clean)
	build-clean
	;;
    *)
	fatal "Unknown command $1"
	;;
esac

exit 0