/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.12.6-arm1
 * Tue Nov  1 19:52:53 2011
 */
#define AUTOCONF_INCLUDED
#define CONFIG_ARM 1
#define CONFIG_MMU 1
#define CONFIG_UID16 1
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_GENERIC_IOMAP 1
#define CONFIG_FIQ 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_LOCK_KERNEL 1
#define CONFIG_INIT_ENV_ARG_LIMIT 32

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#define CONFIG_POSIX_MQUEUE 1
#define CONFIG_BSD_PROCESS_ACCT 1
#define CONFIG_BSD_PROCESS_ACCT_V3 1
#define CONFIG_SYSCTL 1
#define CONFIG_AUDIT 1
#define CONFIG_HOTPLUG 1
#define CONFIG_KOBJECT_UEVENT 1
#undef CONFIG_IKCONFIG
#define CONFIG_CPUSETS 1
#undef CONFIG_EMBEDDED
#define CONFIG_KALLSYMS 1
#define CONFIG_KALLSYMS_ALL 1
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_PRINTK 1
#define CONFIG_BUG 1
#define CONFIG_BASE_FULL 1
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#define CONFIG_CC_OPTIMIZE_FOR_SIZE 1
#define CONFIG_SHMEM 1
#define CONFIG_CC_ALIGN_FUNCTIONS 0
#define CONFIG_CC_ALIGN_LABELS 0
#define CONFIG_CC_ALIGN_LOOPS 0
#define CONFIG_CC_ALIGN_JUMPS 0
#undef CONFIG_TINY_SHMEM
#define CONFIG_BASE_SMALL 0

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#undef CONFIG_MODULE_FORCE_UNLOAD
#define CONFIG_OBSOLETE_MODPARM 1
#define CONFIG_MODVERSIONS 1
#define CONFIG_MODULE_SRCVERSION_ALL 1
#undef CONFIG_KMOD
#define CONFIG_STOP_MACHINE 1

/*
 * System Type
 */
#undef CONFIG_ARCH_CLPS7500
#undef CONFIG_ARCH_CLPS711X
#undef CONFIG_ARCH_CO285
#undef CONFIG_ARCH_EBSA110
#undef CONFIG_ARCH_CAMELOT
#undef CONFIG_ARCH_FOOTBRIDGE
#undef CONFIG_ARCH_INTEGRATOR
#undef CONFIG_ARCH_MV88fxx81
#undef CONFIG_ARCH_IOP3XX
#undef CONFIG_ARCH_IXP4XX
#undef CONFIG_ARCH_IXP2000
#undef CONFIG_ARCH_L7200
#undef CONFIG_ARCH_PXA
#define CONFIG_ARCH_RPC 1
#undef CONFIG_ARCH_SA1100
#undef CONFIG_ARCH_S3C2410
#undef CONFIG_ARCH_SHARK
#undef CONFIG_ARCH_LH7A40X
#undef CONFIG_ARCH_OMAP
#undef CONFIG_ARCH_VERSATILE
#undef CONFIG_ARCH_IMX
#undef CONFIG_ARCH_H720X
#define CONFIG_ARCH_ACORN 1

/*
 * Processor Type
 */
#define CONFIG_CPU_32 1
#undef CONFIG_CPU_ARM610
#undef CONFIG_CPU_ARM710
#undef CONFIG_CPU_SA110

/*
 * Processor Features
 */
#define CONFIG_HAS_TLS_REG 1
#define CONFIG_TIMER_ACORN 1

/*
 * Bus support
 */
#define CONFIG_ISA_DMA_API 1

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#define CONFIG_PCCARD_MODULE 1
#undef CONFIG_PCMCIA_DEBUG
#define CONFIG_PCMCIA_MODULE 1

/*
 * PC-card bridges
 */
#undef CONFIG_TCIC

/*
 * Kernel Features
 */
#define CONFIG_SMP 1
#define CONFIG_NR_CPUS 256
#undef CONFIG_PREEMPT
#undef CONFIG_AEABI
#undef CONFIG_DISCONTIGMEM
#define CONFIG_ALIGNMENT_TRAP 1

/*
 * Boot options
 */
#define CONFIG_ZBOOT_ROM_TEXT 0x0
#define CONFIG_ZBOOT_ROM_BSS 0x0
#define CONFIG_CMDLINE ""
#undef CONFIG_XIP_KERNEL

/*
 * Floating point emulation
 */

/*
 * At least one emulation must be selected
 */
#undef CONFIG_FPE_NWFPE
#undef CONFIG_FPE_FASTFPE
#undef CONFIG_VFP_RUN_FAST_MODE

/*
 * Userspace binary formats
 */
#define CONFIG_BINFMT_ELF 1
#undef CONFIG_BINFMT_AOUT
#define CONFIG_BINFMT_MISC_MODULE 1
#undef CONFIG_ARTHUR

/*
 * Power management options
 */
#define CONFIG_PM 1
#undef CONFIG_APM

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#undef CONFIG_STANDALONE
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#define CONFIG_FW_LOADER 1
#undef CONFIG_DEBUG_DRIVER

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD_MODULE 1
#undef CONFIG_MTD_DEBUG
#undef CONFIG_MTD_CONCAT
#undef CONFIG_MTD_PARTITIONS

/*
 * User Modules And Translation Layers
 */
#define CONFIG_MTD_CHAR_MODULE 1
#define CONFIG_MTD_BLOCK_MODULE 1
#define CONFIG_MTD_BLOCK_RO_MODULE 1
#define CONFIG_FTL_MODULE 1
#define CONFIG_NFTL_MODULE 1
#define CONFIG_NFTL_RW 1
#define CONFIG_INFTL_MODULE 1

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI_MODULE 1
#define CONFIG_MTD_JEDECPROBE_MODULE 1
#define CONFIG_MTD_GEN_PROBE_MODULE 1
#undef CONFIG_MTD_CFI_ADV_OPTIONS
#define CONFIG_MTD_MAP_BANK_WIDTH_1 1
#define CONFIG_MTD_MAP_BANK_WIDTH_2 1
#define CONFIG_MTD_MAP_BANK_WIDTH_4 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_8
#undef CONFIG_MTD_MAP_BANK_WIDTH_16
#undef CONFIG_MTD_MAP_BANK_WIDTH_32
#define CONFIG_MTD_CFI_I1 1
#define CONFIG_MTD_CFI_I2 1
#undef CONFIG_MTD_CFI_I4
#undef CONFIG_MTD_CFI_I8
#define CONFIG_MTD_CFI_INTELEXT_MODULE 1
#define CONFIG_MTD_CFI_AMDSTD_MODULE 1
#define CONFIG_MTD_CFI_AMDSTD_RETRY 0
#define CONFIG_MTD_CFI_STAA_MODULE 1
#define CONFIG_MTD_CFI_UTIL_MODULE 1
#define CONFIG_MTD_RAM_MODULE 1
#define CONFIG_MTD_ROM_MODULE 1
#define CONFIG_MTD_ABSENT_MODULE 1

/*
 * Mapping drivers for chip access
 */
#define CONFIG_MTD_COMPLEX_MAPPINGS 1
#define CONFIG_MTD_PHYSMAP_MODULE 1
#define CONFIG_MTD_PHYSMAP_START 0x8000000
#define CONFIG_MTD_PHYSMAP_LEN 0x4000000
#define CONFIG_MTD_PHYSMAP_BANKWIDTH 2
#undef CONFIG_MTD_ARM_INTEGRATOR
#undef CONFIG_MTD_EDB7312
#undef CONFIG_MTD_IMPA7

/*
 * Self-contained MTD device drivers
 */
#define CONFIG_MTD_SLRAM_MODULE 1
#define CONFIG_MTD_PHRAM_MODULE 1
#define CONFIG_MTD_MTDRAM_MODULE 1
#define CONFIG_MTDRAM_TOTAL_SIZE 4096
#define CONFIG_MTDRAM_ERASE_SIZE 128
#undef CONFIG_MTD_BLKMTD
#define CONFIG_MTD_BLOCK2MTD_MODULE 1

/*
 * Disk-On-Chip Device Drivers
 */
#define CONFIG_MTD_DOC2000_MODULE 1
#define CONFIG_MTD_DOC2001_MODULE 1
#define CONFIG_MTD_DOC2001PLUS_MODULE 1
#define CONFIG_MTD_DOCPROBE_MODULE 1
#define CONFIG_MTD_DOCECC_MODULE 1
#undef CONFIG_MTD_DOCPROBE_ADVANCED
#define CONFIG_MTD_DOCPROBE_ADDRESS 0x0

/*
 * NAND Flash Device Drivers
 */
#define CONFIG_MTD_NAND_MODULE 1
#undef CONFIG_MTD_NAND_VERIFY_WRITE
#define CONFIG_MTD_NAND_IDS_MODULE 1
#define CONFIG_MTD_NAND_DISKONCHIP_MODULE 1
#undef CONFIG_MTD_NAND_DISKONCHIP_PROBE_ADVANCED
#define CONFIG_MTD_NAND_DISKONCHIP_PROBE_ADDRESS 0x0
#undef CONFIG_MTD_NAND_DISKONCHIP_BBTWRITE

/*
 * Parallel port support
 */
#define CONFIG_PARPORT_MODULE 1
#define CONFIG_PARPORT_PC_MODULE 1
#define CONFIG_PARPORT_PC_FIFO 1
#undef CONFIG_PARPORT_PC_SUPERIO
#define CONFIG_PARPORT_PC_PCMCIA_MODULE 1
#define CONFIG_PARPORT_NOT_PC 1
#undef CONFIG_PARPORT_ARC
#undef CONFIG_PARPORT_GSC
#define CONFIG_PARPORT_1284 1

/*
 * Plug and Play support
 */

/*
 * Block devices
 */
#define CONFIG_BLK_DEV_FD_MODULE 1
#define CONFIG_PARIDE_MODULE 1
#define CONFIG_PARIDE_PARPORT_MODULE 1

/*
 * Parallel IDE high-level drivers
 */
#define CONFIG_PARIDE_PD_MODULE 1
#define CONFIG_PARIDE_PCD_MODULE 1
#define CONFIG_PARIDE_PF_MODULE 1
#define CONFIG_PARIDE_PT_MODULE 1
#define CONFIG_PARIDE_PG_MODULE 1

/*
 * Parallel IDE protocol modules
 */
#define CONFIG_PARIDE_ATEN_MODULE 1
#define CONFIG_PARIDE_BPCK_MODULE 1
#undef CONFIG_PARIDE_BPCK6
#define CONFIG_PARIDE_COMM_MODULE 1
#define CONFIG_PARIDE_DSTR_MODULE 1
#define CONFIG_PARIDE_FIT2_MODULE 1
#define CONFIG_PARIDE_FIT3_MODULE 1
#define CONFIG_PARIDE_EPAT_MODULE 1
#undef CONFIG_PARIDE_EPATC8
#define CONFIG_PARIDE_EPIA_MODULE 1
#define CONFIG_PARIDE_FRIQ_MODULE 1
#define CONFIG_PARIDE_FRPW_MODULE 1
#define CONFIG_PARIDE_KBIC_MODULE 1
#define CONFIG_PARIDE_KTTI_MODULE 1
#define CONFIG_PARIDE_ON20_MODULE 1
#define CONFIG_PARIDE_ON26_MODULE 1
#undef CONFIG_BLK_DEV_COW_COMMON
#define CONFIG_BLK_DEV_LOOP 1
#define CONFIG_BLK_DEV_CRYPTOLOOP_MODULE 1
#define CONFIG_BLK_DEV_NBD_MODULE 1
#undef CONFIG_BLK_DEV_UB
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_COUNT 16
#define CONFIG_BLK_DEV_RAM_SIZE 65536
#define CONFIG_BLK_DEV_INITRD 1
#define CONFIG_INITRAMFS_SOURCE ""
#undef CONFIG_LBD
#undef CONFIG_LSF
#define CONFIG_CDROM_PKTCDVD_MODULE 1
#define CONFIG_CDROM_PKTCDVD_BUFFERS 8
#undef CONFIG_CDROM_PKTCDVD_WCACHE

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#define CONFIG_IOSCHED_DEADLINE 1
#define CONFIG_IOSCHED_CFQ 1
#define CONFIG_ATA_OVER_ETH_MODULE 1

/*
 * Acorn-specific block devices
 */

/*
 * ATA/ATAPI/MFM/RLL support
 */
#undef CONFIG_IDE

/*
 * SCSI device support
 */
#define CONFIG_SCSI 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD 1
#define CONFIG_CHR_DEV_ST_MODULE 1
#define CONFIG_CHR_DEV_OSST_MODULE 1
#define CONFIG_BLK_DEV_SR 1
#undef CONFIG_BLK_DEV_SR_VENDOR
#define CONFIG_CHR_DEV_SG 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#define CONFIG_SCSI_MULTI_LUN 1
#define CONFIG_SCSI_CONSTANTS 1
#define CONFIG_SCSI_LOGGING 1

/*
 * SCSI Transport Attributes
 */
#define CONFIG_SCSI_SPI_ATTRS_MODULE 1
#define CONFIG_SCSI_FC_ATTRS_MODULE 1
#define CONFIG_SCSI_ISCSI_ATTRS_MODULE 1

/*
 * SCSI low-level drivers
 */
#undef CONFIG_SCSI_SATA
#define CONFIG_SCSI_PPA_MODULE 1
#define CONFIG_SCSI_IMM_MODULE 1
#undef CONFIG_SCSI_IZIP_EPP16
#undef CONFIG_SCSI_IZIP_SLOW_CTR
#define CONFIG_SCSI_DEBUG_MODULE 1
#undef CONFIG_SCSI_ACORNSCSI_3
#undef CONFIG_SCSI_ARXESCSI
#undef CONFIG_SCSI_CUMANA_2
#undef CONFIG_SCSI_EESOXSCSI
#undef CONFIG_SCSI_POWERTECSCSI

/*
 * The following drivers are not fully supported
 */
#undef CONFIG_SCSI_CUMANA_1
#undef CONFIG_SCSI_OAK1

/*
 * PCMCIA SCSI adapter support
 */
#define CONFIG_PCMCIA_AHA152X_MODULE 1
#define CONFIG_PCMCIA_FDOMAIN_MODULE 1
#undef CONFIG_PCMCIA_NINJA_SCSI
#define CONFIG_PCMCIA_QLOGIC_MODULE 1
#define CONFIG_PCMCIA_SYM53C500_MODULE 1

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#define CONFIG_BLK_DEV_MD 1
#define CONFIG_MD_LINEAR_MODULE 1
#define CONFIG_MD_RAID0_MODULE 1
#define CONFIG_MD_RAID1_MODULE 1
#define CONFIG_MD_RAID10_MODULE 1
#undef CONFIG_MD_RAID5
#undef CONFIG_MD_RAID6
#define CONFIG_MD_MULTIPATH_MODULE 1
#define CONFIG_MD_FAULTY_MODULE 1
#define CONFIG_BLK_DEV_DM 1
#define CONFIG_DM_CRYPT_MODULE 1
#define CONFIG_DM_SNAPSHOT_MODULE 1
#define CONFIG_DM_MIRROR_MODULE 1
#define CONFIG_DM_ZERO_MODULE 1
#define CONFIG_DM_MULTIPATH_MODULE 1
#undef CONFIG_DM_MULTIPATH_EMC

/*
 * Fusion MPT device support
 */

/*
 * IEEE 1394 (FireWire) support
 */

/*
 * I2O device support
 */

/*
 * Networking support
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#undef CONFIG_PACKET_MMAP
#define CONFIG_UNIX 1
#define CONFIG_NET_KEY_MODULE 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_IP_ADVANCED_ROUTER 1
#define CONFIG_IP_MULTIPLE_TABLES 1
#undef CONFIG_IP_ROUTE_FWMARK
#define CONFIG_IP_ROUTE_MULTIPATH 1
#undef CONFIG_IP_ROUTE_MULTIPATH_CACHED
#define CONFIG_IP_ROUTE_VERBOSE 1
#undef CONFIG_IP_PNP
#define CONFIG_NET_IPIP_MODULE 1
#define CONFIG_NET_IPGRE_MODULE 1
#define CONFIG_NET_IPGRE_BROADCAST 1
#define CONFIG_IP_MROUTE 1
#define CONFIG_IP_PIMSM_V1 1
#define CONFIG_IP_PIMSM_V2 1
#undef CONFIG_ARPD
#define CONFIG_SYN_COOKIES 1
#define CONFIG_INET_AH_MODULE 1
#define CONFIG_INET_ESP_MODULE 1
#define CONFIG_INET_IPCOMP_MODULE 1
#define CONFIG_INET_TUNNEL_MODULE 1
#define CONFIG_IP_TCPDIAG 1
#define CONFIG_IP_TCPDIAG_IPV6 1

/*
 * IP: Virtual Server Configuration
 */
#define CONFIG_IP_VS_MODULE 1
#undef CONFIG_IP_VS_DEBUG
#define CONFIG_IP_VS_TAB_BITS 12

/*
 * IPVS transport protocol load balancing support
 */
#define CONFIG_IP_VS_PROTO_TCP 1
#define CONFIG_IP_VS_PROTO_UDP 1
#define CONFIG_IP_VS_PROTO_ESP 1
#define CONFIG_IP_VS_PROTO_AH 1

/*
 * IPVS scheduler
 */
#define CONFIG_IP_VS_RR_MODULE 1
#define CONFIG_IP_VS_WRR_MODULE 1
#define CONFIG_IP_VS_LC_MODULE 1
#define CONFIG_IP_VS_WLC_MODULE 1
#define CONFIG_IP_VS_LBLC_MODULE 1
#define CONFIG_IP_VS_LBLCR_MODULE 1
#define CONFIG_IP_VS_DH_MODULE 1
#define CONFIG_IP_VS_SH_MODULE 1
#define CONFIG_IP_VS_SED_MODULE 1
#define CONFIG_IP_VS_NQ_MODULE 1

/*
 * IPVS application helper
 */
#define CONFIG_IP_VS_FTP_MODULE 1
#define CONFIG_IPV6 1
#define CONFIG_IPV6_PRIVACY 1
#define CONFIG_INET6_AH_MODULE 1
#define CONFIG_INET6_ESP_MODULE 1
#define CONFIG_INET6_IPCOMP_MODULE 1
#define CONFIG_INET6_TUNNEL_MODULE 1
#define CONFIG_IPV6_TUNNEL_MODULE 1
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG
#define CONFIG_BRIDGE_NETFILTER 1

/*
 * IP: Netfilter Configuration
 */
#undef CONFIG_IP_NF_CONNTRACK
#undef CONFIG_IP_NF_CONNTRACK_MARK
#define CONFIG_IP_NF_QUEUE_MODULE 1
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#undef CONFIG_IP_NF_MATCH_LIMIT
#undef CONFIG_IP_NF_MATCH_IPRANGE
#undef CONFIG_IP_NF_MATCH_MAC
#undef CONFIG_IP_NF_MATCH_PKTTYPE
#undef CONFIG_IP_NF_MATCH_MARK
#undef CONFIG_IP_NF_MATCH_MULTIPORT
#undef CONFIG_IP_NF_MATCH_TOS
#undef CONFIG_IP_NF_MATCH_RECENT
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#undef CONFIG_IP_NF_MATCH_DSCP
#undef CONFIG_IP_NF_MATCH_AH_ESP
#undef CONFIG_IP_NF_MATCH_LENGTH
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#undef CONFIG_IP_NF_MATCH_TCPMSS
#undef CONFIG_IP_NF_MATCH_OWNER
#undef CONFIG_IP_NF_MATCH_PHYSDEV
#undef CONFIG_IP_NF_MATCH_ADDRTYPE
#undef CONFIG_IP_NF_MATCH_REALM
#undef CONFIG_IP_NF_MATCH_SCTP
#undef CONFIG_IP_NF_MATCH_COMMENT
#undef CONFIG_IP_NF_MATCH_HASHLIMIT
#define CONFIG_IP_NF_FILTER_MODULE 1
#define CONFIG_IP_NF_TARGET_REJECT_MODULE 1
#define CONFIG_IP_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#undef CONFIG_IP_NF_TARGET_TCPMSS
#define CONFIG_IP_NF_MANGLE_MODULE 1
#undef CONFIG_IP_NF_TARGET_TOS
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#undef CONFIG_IP_NF_TARGET_DSCP
#undef CONFIG_IP_NF_TARGET_MARK
#undef CONFIG_IP_NF_TARGET_CLASSIFY
#define CONFIG_IP_NF_RAW_MODULE 1
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#define CONFIG_IP_NF_ARPFILTER_MODULE 1
#define CONFIG_IP_NF_ARP_MANGLE_MODULE 1

/*
 * IPv6: Netfilter Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP6_NF_QUEUE_MODULE 1
#define CONFIG_IP6_NF_IPTABLES_MODULE 1
#undef CONFIG_IP6_NF_MATCH_LIMIT
#undef CONFIG_IP6_NF_MATCH_MAC
#define CONFIG_IP6_NF_MATCH_RT_MODULE 1
#define CONFIG_IP6_NF_MATCH_OPTS_MODULE 1
#define CONFIG_IP6_NF_MATCH_FRAG_MODULE 1
#define CONFIG_IP6_NF_MATCH_HL_MODULE 1
#undef CONFIG_IP6_NF_MATCH_MULTIPORT
#undef CONFIG_IP6_NF_MATCH_OWNER
#undef CONFIG_IP6_NF_MATCH_MARK
#define CONFIG_IP6_NF_MATCH_IPV6HEADER_MODULE 1
#undef CONFIG_IP6_NF_MATCH_AHESP
#undef CONFIG_IP6_NF_MATCH_LENGTH
#define CONFIG_IP6_NF_MATCH_EUI64_MODULE 1
#undef CONFIG_IP6_NF_MATCH_PHYSDEV
#define CONFIG_IP6_NF_FILTER_MODULE 1
#define CONFIG_IP6_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP6_NF_MANGLE_MODULE 1
#undef CONFIG_IP6_NF_TARGET_MARK
#define CONFIG_IP6_NF_RAW_MODULE 1

/*
 * DECnet: Netfilter Configuration
 */
#define CONFIG_DECNET_NF_GRABULATOR_MODULE 1

/*
 * Bridge: Netfilter Configuration
 */
#define CONFIG_BRIDGE_NF_EBTABLES_MODULE 1
#define CONFIG_BRIDGE_EBT_BROUTE_MODULE 1
#define CONFIG_BRIDGE_EBT_T_FILTER_MODULE 1
#define CONFIG_BRIDGE_EBT_T_NAT_MODULE 1
#define CONFIG_BRIDGE_EBT_802_3_MODULE 1
#define CONFIG_BRIDGE_EBT_AMONG_MODULE 1
#define CONFIG_BRIDGE_EBT_ARP_MODULE 1
#define CONFIG_BRIDGE_EBT_IP_MODULE 1
#define CONFIG_BRIDGE_EBT_LIMIT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_MODULE 1
#define CONFIG_BRIDGE_EBT_PKTTYPE_MODULE 1
#define CONFIG_BRIDGE_EBT_STP_MODULE 1
#define CONFIG_BRIDGE_EBT_VLAN_MODULE 1
#define CONFIG_BRIDGE_EBT_ARPREPLY_MODULE 1
#define CONFIG_BRIDGE_EBT_DNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_T_MODULE 1
#define CONFIG_BRIDGE_EBT_REDIRECT_MODULE 1
#define CONFIG_BRIDGE_EBT_SNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_LOG_MODULE 1
#define CONFIG_BRIDGE_EBT_ULOG_MODULE 1
#define CONFIG_XFRM 1
#define CONFIG_XFRM_USER_MODULE 1

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP_SCTP_MODULE 1
#undef CONFIG_SCTP_DBG_MSG
#undef CONFIG_SCTP_DBG_OBJCNT
#undef CONFIG_SCTP_HMAC_NONE
#undef CONFIG_SCTP_HMAC_SHA1
#define CONFIG_SCTP_HMAC_MD5 1
#define CONFIG_ATM_MODULE 1
#define CONFIG_ATM_CLIP_MODULE 1
#undef CONFIG_ATM_CLIP_NO_ICMP
#define CONFIG_ATM_LANE_MODULE 1
#define CONFIG_ATM_MPOA_MODULE 1
#define CONFIG_ATM_BR2684_MODULE 1
#undef CONFIG_ATM_BR2684_IPFILTER
#define CONFIG_BRIDGE_MODULE 1
#define CONFIG_VLAN_8021Q_MODULE 1
#define CONFIG_DECNET_MODULE 1
#undef CONFIG_DECNET_ROUTER
#define CONFIG_LLC_MODULE 1
#define CONFIG_LLC2_MODULE 1
#define CONFIG_IPX_MODULE 1
#undef CONFIG_IPX_INTERN
#define CONFIG_ATALK_MODULE 1
#undef CONFIG_DEV_APPLETALK
#define CONFIG_X25_MODULE 1
#define CONFIG_LAPB_MODULE 1
#undef CONFIG_NET_DIVERT
#define CONFIG_ECONET_MODULE 1
#define CONFIG_ECONET_AUNUDP 1
#define CONFIG_ECONET_NATIVE 1
#define CONFIG_WAN_ROUTER_MODULE 1

/*
 * QoS and/or fair queueing
 */
#define CONFIG_NET_SCHED 1
#define CONFIG_NET_SCH_CLK_JIFFIES 1
#undef CONFIG_NET_SCH_CLK_GETTIMEOFDAY
#undef CONFIG_NET_SCH_CLK_CPU
#define CONFIG_NET_SCH_CBQ_MODULE 1
#define CONFIG_NET_SCH_HTB_MODULE 1
#define CONFIG_NET_SCH_HFSC_MODULE 1
#define CONFIG_NET_SCH_ATM_MODULE 1
#define CONFIG_NET_SCH_PRIO_MODULE 1
#define CONFIG_NET_SCH_RED_MODULE 1
#define CONFIG_NET_SCH_SFQ_MODULE 1
#define CONFIG_NET_SCH_TEQL_MODULE 1
#define CONFIG_NET_SCH_TBF_MODULE 1
#define CONFIG_NET_SCH_GRED_MODULE 1
#define CONFIG_NET_SCH_DSMARK_MODULE 1
#define CONFIG_NET_SCH_NETEM_MODULE 1
#define CONFIG_NET_SCH_INGRESS_MODULE 1
#undef CONFIG_NET_QOS
#define CONFIG_NET_CLS 1
#define CONFIG_NET_CLS_BASIC_MODULE 1
#define CONFIG_NET_CLS_TCINDEX_MODULE 1
#define CONFIG_NET_CLS_ROUTE4_MODULE 1
#define CONFIG_NET_CLS_ROUTE 1
#define CONFIG_NET_CLS_FW_MODULE 1
#define CONFIG_NET_CLS_U32_MODULE 1
#undef CONFIG_CLS_U32_PERF
#undef CONFIG_NET_CLS_IND
#define CONFIG_CLS_U32_MARK 1
#define CONFIG_NET_EMATCH 1
#define CONFIG_NET_EMATCH_STACK 32
#define CONFIG_NET_EMATCH_CMP_MODULE 1
#define CONFIG_NET_EMATCH_NBYTE_MODULE 1
#define CONFIG_NET_EMATCH_U32_MODULE 1
#define CONFIG_NET_EMATCH_META_MODULE 1

/*
 * Network testing
 */
#define CONFIG_NET_PKTGEN_MODULE 1
#define CONFIG_NETPOLL 1
#undef CONFIG_NETPOLL_RX
#undef CONFIG_NETPOLL_TRAP
#define CONFIG_NET_POLL_CONTROLLER 1
#define CONFIG_HAMRADIO 1

/*
 * Packet Radio protocols
 */
#define CONFIG_AX25_MODULE 1
#define CONFIG_AX25_DAMA_SLAVE 1
#define CONFIG_NETROM_MODULE 1
#define CONFIG_ROSE_MODULE 1

/*
 * AX.25 network device drivers
 */
#define CONFIG_6PACK_MODULE 1
#define CONFIG_BPQETHER_MODULE 1
#define CONFIG_BAYCOM_SER_FDX_MODULE 1
#define CONFIG_BAYCOM_SER_HDX_MODULE 1
#define CONFIG_BAYCOM_PAR_MODULE 1
#undef CONFIG_BAYCOM_EPP
#define CONFIG_YAM_MODULE 1
#define CONFIG_IRDA_MODULE 1

/*
 * IrDA protocols
 */
#define CONFIG_IRLAN_MODULE 1
#define CONFIG_IRNET_MODULE 1
#define CONFIG_IRCOMM_MODULE 1
#define CONFIG_IRDA_ULTRA 1

/*
 * IrDA options
 */
#define CONFIG_IRDA_CACHE_LAST_LSAP 1
#define CONFIG_IRDA_FAST_RR 1
#define CONFIG_IRDA_DEBUG 1

/*
 * Infrared-port device drivers
 */

/*
 * SIR device drivers
 */
#define CONFIG_IRTTY_SIR_MODULE 1

/*
 * Dongle support
 */
#define CONFIG_DONGLE 1
#define CONFIG_ESI_DONGLE_MODULE 1
#define CONFIG_ACTISYS_DONGLE_MODULE 1
#define CONFIG_TEKRAM_DONGLE_MODULE 1
#define CONFIG_LITELINK_DONGLE_MODULE 1
#define CONFIG_MA600_DONGLE_MODULE 1
#define CONFIG_GIRBIL_DONGLE_MODULE 1
#define CONFIG_MCP2120_DONGLE_MODULE 1
#define CONFIG_OLD_BELKIN_DONGLE_MODULE 1
#define CONFIG_ACT200L_DONGLE_MODULE 1

/*
 * Old SIR device drivers
 */

/*
 * Old Serial dongle support
 */

/*
 * FIR device drivers
 */
#define CONFIG_USB_IRDA_MODULE 1
#define CONFIG_SIGMATEL_FIR_MODULE 1
#define CONFIG_NSC_FIR_MODULE 1
#define CONFIG_WINBOND_FIR_MODULE 1
#define CONFIG_SMC_IRCC_FIR_MODULE 1
#define CONFIG_ALI_FIR_MODULE 1
#define CONFIG_VIA_FIR_MODULE 1
#define CONFIG_BT_MODULE 1
#define CONFIG_BT_L2CAP_MODULE 1
#define CONFIG_BT_SCO_MODULE 1
#define CONFIG_BT_RFCOMM_MODULE 1
#define CONFIG_BT_RFCOMM_TTY 1
#define CONFIG_BT_BNEP_MODULE 1
#define CONFIG_BT_BNEP_MC_FILTER 1
#define CONFIG_BT_BNEP_PROTO_FILTER 1
#define CONFIG_BT_CMTP_MODULE 1
#define CONFIG_BT_HIDP_MODULE 1

/*
 * Bluetooth device drivers
 */
#undef CONFIG_BT_HCIUSB
#define CONFIG_BT_HCIUART_MODULE 1
#define CONFIG_BT_HCIUART_H4 1
#define CONFIG_BT_HCIUART_BCSP 1
#undef CONFIG_BT_HCIUART_BCSP_TXCRC
#define CONFIG_BT_HCIBCM203X_MODULE 1
#define CONFIG_BT_HCIBPA10X_MODULE 1
#define CONFIG_BT_HCIBFUSB_MODULE 1
#define CONFIG_BT_HCIDTL1_MODULE 1
#define CONFIG_BT_HCIBT3C_MODULE 1
#define CONFIG_BT_HCIBLUECARD_MODULE 1
#define CONFIG_BT_HCIBTUART_MODULE 1
#define CONFIG_BT_HCIVHCI_MODULE 1
#define CONFIG_NETDEVICES 1
#define CONFIG_DUMMY_MODULE 1
#define CONFIG_BONDING_MODULE 1
#define CONFIG_EQUALIZER_MODULE 1
#define CONFIG_TUN 1

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_MII 1
#undef CONFIG_ARM_ETHER1
#undef CONFIG_ARM_ETHER3
#undef CONFIG_ARM_ETHERH
#undef CONFIG_SMC91X

/*
 * Ethernet (1000 Mbit)
 */

/*
 * Ethernet (10000 Mbit)
 */

/*
 * Token Ring devices
 */

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1

/*
 * Obsolete Wireless cards support (pre-802.11)
 */
#undef CONFIG_STRIP
#undef CONFIG_PCMCIA_WAVELAN
#undef CONFIG_PCMCIA_NETWAVE

/*
 * Wireless 802.11 Frequency Hopping cards support
 */
#define CONFIG_PCMCIA_RAYCS_MODULE 1

/*
 * Wireless 802.11b ISA/PCI cards support
 */
#define CONFIG_HERMES_MODULE 1
#define CONFIG_ATMEL_MODULE 1

/*
 * Wireless 802.11b Pcmcia/Cardbus cards support
 */
#define CONFIG_PCMCIA_HERMES_MODULE 1
#define CONFIG_AIRO_CS_MODULE 1
#define CONFIG_PCMCIA_ATMEL_MODULE 1
#define CONFIG_PCMCIA_WL3501_MODULE 1
#undef CONFIG_MARVELL_HARDAP
#undef CONFIG_MARVELL_SOFTAP
#define CONFIG_NET_WIRELESS 1

/*
 * PCMCIA network device support
 */
#define CONFIG_NET_PCMCIA 1
#define CONFIG_PCMCIA_3C589_MODULE 1
#define CONFIG_PCMCIA_3C574_MODULE 1
#define CONFIG_PCMCIA_FMVJ18X_MODULE 1
#define CONFIG_PCMCIA_PCNET_MODULE 1
#define CONFIG_PCMCIA_NMCLAN_MODULE 1
#define CONFIG_PCMCIA_SMC91C92_MODULE 1
#define CONFIG_PCMCIA_XIRC2PS_MODULE 1
#define CONFIG_PCMCIA_AXNET_MODULE 1

/*
 * Wan interfaces
 */
#define CONFIG_WAN 1
#undef CONFIG_SYNCLINK_SYNCPPP
#define CONFIG_HDLC_MODULE 1
#undef CONFIG_HDLC_RAW
#undef CONFIG_HDLC_RAW_ETH
#undef CONFIG_HDLC_CISCO
#undef CONFIG_HDLC_FR
#undef CONFIG_HDLC_PPP
#undef CONFIG_HDLC_X25
#define CONFIG_DLCI_MODULE 1
#define CONFIG_DLCI_COUNT 24
#define CONFIG_DLCI_MAX 8
#undef CONFIG_WAN_ROUTER_DRIVERS
#define CONFIG_LAPBETHER_MODULE 1
#define CONFIG_X25_ASY_MODULE 1

/*
 * ATM drivers
 */
#define CONFIG_ATM_TCP_MODULE 1
#define CONFIG_PLIP_MODULE 1
#define CONFIG_PPP 1
#define CONFIG_PPP_MULTILINK 1
#define CONFIG_PPP_FILTER 1
#define CONFIG_PPP_ASYNC_MODULE 1
#define CONFIG_PPP_SYNC_TTY_MODULE 1
#define CONFIG_PPP_DEFLATE_MODULE 1
#define CONFIG_PPP_BSDCOMP_MODULE 1
#define CONFIG_PPPOE_MODULE 1
#define CONFIG_PPPOATM_MODULE 1
#define CONFIG_SLIP_MODULE 1
#define CONFIG_SLIP_COMPRESSED 1
#define CONFIG_SLIP_SMART 1
#define CONFIG_SLIP_MODE_SLIP6 1
#undef CONFIG_SHAPER
#define CONFIG_NETCONSOLE_MODULE 1

/*
 * ISDN subsystem
 */
#define CONFIG_ISDN 1

/*
 * Old ISDN4Linux
 */
#define CONFIG_ISDN_I4L_MODULE 1
#define CONFIG_ISDN_PPP 1
#define CONFIG_ISDN_PPP_VJ 1
#define CONFIG_ISDN_MPP 1
#define CONFIG_IPPP_FILTER 1
#define CONFIG_ISDN_PPP_BSDCOMP_MODULE 1
#define CONFIG_ISDN_AUDIO 1
#define CONFIG_ISDN_TTY_FAX 1
#define CONFIG_ISDN_X25 1

/*
 * ISDN feature submodules
 */
#define CONFIG_ISDN_DIVERSION_MODULE 1

/*
 * ISDN4Linux hardware drivers
 */

/*
 * Passive cards
 */
#define CONFIG_ISDN_DRV_HISAX_MODULE 1

/*
 * D-channel protocol features
 */
#define CONFIG_HISAX_EURO 1
#define CONFIG_DE_AOC 1
#undef CONFIG_HISAX_NO_SENDCOMPLETE
#undef CONFIG_HISAX_NO_LLC
#undef CONFIG_HISAX_NO_KEYPAD
#define CONFIG_HISAX_1TR6 1
#define CONFIG_HISAX_NI1 1
#define CONFIG_HISAX_MAX_CARDS 8

/*
 * HiSax supported cards
 */
#define CONFIG_HISAX_16_3 1
#define CONFIG_HISAX_S0BOX 1
#define CONFIG_HISAX_FRITZPCI 1
#define CONFIG_HISAX_AVM_A1_PCMCIA 1
#define CONFIG_HISAX_ELSA 1
#define CONFIG_HISAX_DIEHLDIVA 1
#define CONFIG_HISAX_SEDLBAUER 1
#define CONFIG_HISAX_NICCY 1
#define CONFIG_HISAX_GAZEL 1
#define CONFIG_HISAX_HFC_SX 1
#undef CONFIG_HISAX_DEBUG

/*
 * HiSax PCMCIA card service modules
 */
#define CONFIG_HISAX_SEDLBAUER_CS_MODULE 1
#define CONFIG_HISAX_ELSA_CS_MODULE 1
#define CONFIG_HISAX_AVM_A1_CS_MODULE 1
#define CONFIG_HISAX_TELES_CS_MODULE 1

/*
 * HiSax sub driver modules
 */
#define CONFIG_HISAX_ST5481_MODULE 1
#define CONFIG_HISAX_HFCUSB_MODULE 1
#define CONFIG_HISAX_HFC4S8S_MODULE 1
#define CONFIG_HISAX_HDLC 1

/*
 * Active cards
 */

/*
 * CAPI subsystem
 */
#define CONFIG_ISDN_CAPI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_VERBOSE_REASON 1
#define CONFIG_ISDN_CAPI_MIDDLEWARE 1
#define CONFIG_ISDN_CAPI_CAPI20_MODULE 1
#undef CONFIG_ISDN_CAPI_CAPIFS_BOOL
#define CONFIG_ISDN_CAPI_CAPIDRV_MODULE 1

/*
 * CAPI hardware drivers
 */

/*
 * Active AVM cards
 */
#define CONFIG_CAPI_AVM 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCMCIA_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_AVM_CS_MODULE 1

/*
 * Active Eicon DIVA Server cards
 */
#define CONFIG_CAPI_EICON 1

/*
 * Telephony Support
 */
#define CONFIG_PHONE_MODULE 1
#define CONFIG_PHONE_IXJ_MODULE 1
#define CONFIG_PHONE_IXJ_PCMCIA_MODULE 1

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#define CONFIG_INPUT_MOUSEDEV 1
#define CONFIG_INPUT_MOUSEDEV_PSAUX 1
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768
#define CONFIG_INPUT_JOYDEV_MODULE 1
#undef CONFIG_INPUT_TSDEV
#define CONFIG_INPUT_EVDEV 1
#define CONFIG_INPUT_EVBUG_MODULE 1

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#define CONFIG_KEYBOARD_ATKBD 1
#define CONFIG_KEYBOARD_SUNKBD_MODULE 1
#define CONFIG_KEYBOARD_LKKBD_MODULE 1
#define CONFIG_KEYBOARD_XTKBD_MODULE 1
#define CONFIG_KEYBOARD_NEWTON_MODULE 1
#define CONFIG_INPUT_MOUSE 1
#define CONFIG_MOUSE_PS2_MODULE 1
#define CONFIG_MOUSE_SERIAL_MODULE 1
#undef CONFIG_MOUSE_RISCPC
#define CONFIG_MOUSE_VSXXXAA_MODULE 1
#define CONFIG_INPUT_JOYSTICK 1
#define CONFIG_JOYSTICK_ANALOG_MODULE 1
#define CONFIG_JOYSTICK_A3D_MODULE 1
#define CONFIG_JOYSTICK_ADI_MODULE 1
#define CONFIG_JOYSTICK_COBRA_MODULE 1
#define CONFIG_JOYSTICK_GF2K_MODULE 1
#define CONFIG_JOYSTICK_GRIP_MODULE 1
#define CONFIG_JOYSTICK_GRIP_MP_MODULE 1
#define CONFIG_JOYSTICK_GUILLEMOT_MODULE 1
#define CONFIG_JOYSTICK_INTERACT_MODULE 1
#define CONFIG_JOYSTICK_SIDEWINDER_MODULE 1
#define CONFIG_JOYSTICK_TMDC_MODULE 1
#define CONFIG_JOYSTICK_IFORCE_MODULE 1
#define CONFIG_JOYSTICK_IFORCE_USB 1
#define CONFIG_JOYSTICK_IFORCE_232 1
#define CONFIG_JOYSTICK_WARRIOR_MODULE 1
#define CONFIG_JOYSTICK_MAGELLAN_MODULE 1
#define CONFIG_JOYSTICK_SPACEORB_MODULE 1
#define CONFIG_JOYSTICK_SPACEBALL_MODULE 1
#define CONFIG_JOYSTICK_STINGER_MODULE 1
#define CONFIG_JOYSTICK_TWIDJOY_MODULE 1
#define CONFIG_JOYSTICK_DB9_MODULE 1
#define CONFIG_JOYSTICK_GAMECON_MODULE 1
#define CONFIG_JOYSTICK_TURBOGRAFX_MODULE 1
#define CONFIG_JOYSTICK_JOYDUMP_MODULE 1
#define CONFIG_INPUT_TOUCHSCREEN 1
#define CONFIG_TOUCHSCREEN_GUNZE_MODULE 1
#define CONFIG_TOUCHSCREEN_ELO_MODULE 1
#define CONFIG_TOUCHSCREEN_MTOUCH_MODULE 1
#define CONFIG_TOUCHSCREEN_MK712_MODULE 1
#define CONFIG_INPUT_MISC 1
#define CONFIG_INPUT_UINPUT 1

/*
 * Hardware I/O ports
 */
#define CONFIG_SERIO 1
#define CONFIG_SERIO_SERPORT_MODULE 1
#define CONFIG_SERIO_PARKBD_MODULE 1
#define CONFIG_SERIO_RPCKBD 1
#define CONFIG_SERIO_LIBPS2 1
#define CONFIG_SERIO_RAW_MODULE 1
#define CONFIG_GAMEPORT_MODULE 1
#define CONFIG_GAMEPORT_NS558_MODULE 1
#define CONFIG_GAMEPORT_L4_MODULE 1

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#define CONFIG_SERIAL_NONSTANDARD 1
#define CONFIG_ROCKETPORT_MODULE 1
#define CONFIG_CYCLADES_MODULE 1
#undef CONFIG_CYZ_INTR
#define CONFIG_MOXA_SMARTIO_MODULE 1
#undef CONFIG_ISI
#define CONFIG_SYNCLINKMP_MODULE 1
#define CONFIG_N_HDLC_MODULE 1
#define CONFIG_SPECIALIX_MODULE 1
#undef CONFIG_SPECIALIX_RTSCTS
#undef CONFIG_SX
#define CONFIG_STALDRV 1

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250 1
#define CONFIG_SERIAL_8250_CONSOLE 1
#define CONFIG_SERIAL_8250_CS_MODULE 1
#define CONFIG_SERIAL_8250_NR_UARTS 48
#define CONFIG_SERIAL_8250_EXTENDED 1
#define CONFIG_SERIAL_8250_MANY_PORTS 1
#define CONFIG_SERIAL_8250_SHARE_IRQ 1
#undef CONFIG_SERIAL_8250_DETECT_IRQ
#undef CONFIG_SERIAL_8250_MULTIPORT
#define CONFIG_SERIAL_8250_RSA 1

/*
 * Non-8250 serial port support
 */
#undef CONFIG_SERIAL_8250_ACORN
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_LEGACY_PTYS 1
#define CONFIG_LEGACY_PTY_COUNT 0
#define CONFIG_PRINTER_MODULE 1
#undef CONFIG_LP_CONSOLE
#define CONFIG_PPDEV_MODULE 1
#undef CONFIG_TIPAR

/*
 * IPMI
 */
#define CONFIG_IPMI_HANDLER_MODULE 1
#undef CONFIG_IPMI_PANIC_EVENT
#define CONFIG_IPMI_DEVICE_INTERFACE_MODULE 1
#define CONFIG_IPMI_SI_MODULE 1
#define CONFIG_IPMI_WATCHDOG_MODULE 1
#define CONFIG_IPMI_POWEROFF_MODULE 1

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef CONFIG_WATCHDOG_NOWAYOUT

/*
 * Watchdog Device Drivers
 */
#define CONFIG_SOFT_WATCHDOG_MODULE 1

/*
 * USB-based Watchdog Cards
 */
#define CONFIG_USBPCWATCHDOG_MODULE 1
#define CONFIG_NVRAM_MODULE 1
#undef CONFIG_RTC
#undef CONFIG_DTLK
#define CONFIG_R3964_MODULE 1

/*
 * Ftape, the floppy tape device driver
 */
#define CONFIG_DRM_MODULE 1

/*
 * PCMCIA character devices
 */
#define CONFIG_SYNCLINK_CS_MODULE 1
#define CONFIG_RAW_DRIVER_MODULE 1
#define CONFIG_MAX_RAW_DEVS 256

/*
 * TPM devices
 */

/*
 * I2C support
 */
#define CONFIG_I2C 1
#define CONFIG_I2C_CHARDEV_MODULE 1

/*
 * I2C Algorithms
 */
#define CONFIG_I2C_ALGOBIT_MODULE 1
#define CONFIG_I2C_ALGOPCF_MODULE 1
#define CONFIG_I2C_ALGOPCA_MODULE 1

/*
 * I2C Hardware Bus support
 */
#define CONFIG_I2C_ISA_MODULE 1
#define CONFIG_I2C_PARPORT_MODULE 1
#define CONFIG_I2C_PARPORT_LIGHT_MODULE 1
#define CONFIG_I2C_STUB_MODULE 1
#undef CONFIG_I2C_PCA_ISA

/*
 * Hardware Sensors Chip support
 */
#define CONFIG_I2C_SENSOR_MODULE 1
#define CONFIG_SENSORS_ADM1021_MODULE 1
#define CONFIG_SENSORS_ADM1025_MODULE 1
#define CONFIG_SENSORS_ADM1026_MODULE 1
#define CONFIG_SENSORS_ADM1031_MODULE 1
#define CONFIG_SENSORS_ASB100_MODULE 1
#define CONFIG_SENSORS_DS1621_MODULE 1
#undef CONFIG_SENSORS_FSCHER
#undef CONFIG_SENSORS_FSCPOS
#define CONFIG_SENSORS_GL518SM_MODULE 1
#define CONFIG_SENSORS_GL520SM_MODULE 1
#define CONFIG_SENSORS_IT87_MODULE 1
#define CONFIG_SENSORS_LM63_MODULE 1
#define CONFIG_SENSORS_LM75_MODULE 1
#define CONFIG_SENSORS_LM77_MODULE 1
#define CONFIG_SENSORS_LM78_MODULE 1
#define CONFIG_SENSORS_LM80_MODULE 1
#define CONFIG_SENSORS_LM83_MODULE 1
#define CONFIG_SENSORS_LM85_MODULE 1
#define CONFIG_SENSORS_LM87_MODULE 1
#define CONFIG_SENSORS_LM90_MODULE 1
#define CONFIG_SENSORS_LM92_MODULE 1
#define CONFIG_SENSORS_MAX1619_MODULE 1
#define CONFIG_SENSORS_PC87360_MODULE 1
#define CONFIG_SENSORS_SMSC47B397_MODULE 1
#define CONFIG_SENSORS_SMSC47M1_MODULE 1
#define CONFIG_SENSORS_W83781D_MODULE 1
#define CONFIG_SENSORS_W83L785TS_MODULE 1
#define CONFIG_SENSORS_W83627HF_MODULE 1

/*
 * Other I2C Chip support
 */
#undef CONFIG_SENSORS_DS1337
#undef CONFIG_SENSORS_EEPROM
#undef CONFIG_SENSORS_PCF8574
#define CONFIG_SENSORS_PCF8591_MODULE 1
#undef CONFIG_SENSORS_RTC8564
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * Misc devices
 */

/*
 * Multimedia devices
 */
#define CONFIG_VIDEO_DEV_MODULE 1

/*
 * Video For Linux
 */

/*
 * Video Adapters
 */
#define CONFIG_VIDEO_BWQCAM_MODULE 1
#define CONFIG_VIDEO_CQCAM_MODULE 1
#define CONFIG_VIDEO_W9966_MODULE 1
#undef CONFIG_VIDEO_CPIA
#undef CONFIG_VIDEO_SAA5246A
#undef CONFIG_VIDEO_SAA5249
#undef CONFIG_TUNER_3036
#undef CONFIG_VIDEO_OVCAMCHIP

/*
 * Radio Adapters
 */
#undef CONFIG_RADIO_MAESTRO

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB

/*
 * Graphics support
 */
#define CONFIG_FB 1
#define CONFIG_FB_CFB_FILLRECT_MODULE 1
#define CONFIG_FB_CFB_COPYAREA_MODULE 1
#define CONFIG_FB_CFB_IMAGEBLIT_MODULE 1
#define CONFIG_FB_SOFT_CURSOR_MODULE 1
#undef CONFIG_FB_MACMODES
#define CONFIG_FB_MODE_HELPERS 1
#define CONFIG_FB_TILEBLITTING 1
#undef CONFIG_FB_ACORN
#define CONFIG_FB_S1D13XXX_MODULE 1
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE 1
#undef CONFIG_FONTS
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1
#define CONFIG_FONT_ACORN_8x8 1

/*
 * Logo configuration
 */
#undef CONFIG_LOGO
#define CONFIG_BACKLIGHT_LCD_SUPPORT 1
#define CONFIG_BACKLIGHT_CLASS_DEVICE 1
#define CONFIG_BACKLIGHT_DEVICE 1
#define CONFIG_LCD_CLASS_DEVICE_MODULE 1
#define CONFIG_LCD_DEVICE 1

/*
 * Sound
 */
#define CONFIG_SOUND_MODULE 1

/*
 * Advanced Linux Sound Architecture
 */
#define CONFIG_SND_MODULE 1
#define CONFIG_SND_TIMER_MODULE 1
#define CONFIG_SND_PCM_MODULE 1
#define CONFIG_SND_RAWMIDI_MODULE 1
#define CONFIG_SND_SEQUENCER_MODULE 1
#define CONFIG_SND_SEQ_DUMMY_MODULE 1
#undef CONFIG_SND_MIXER_OSS
#undef CONFIG_SND_PCM_OSS
#undef CONFIG_SND_SEQUENCER_OSS
#undef CONFIG_SND_VERBOSE_PRINTK
#undef CONFIG_SND_DEBUG

/*
 * Generic devices
 */
#define CONFIG_SND_MPU401_UART_MODULE 1
#define CONFIG_SND_DUMMY_MODULE 1
#define CONFIG_SND_VIRMIDI_MODULE 1
#define CONFIG_SND_MTPAV_MODULE 1
#define CONFIG_SND_SERIAL_U16550_MODULE 1
#define CONFIG_SND_MPU401_MODULE 1

/*
 * ALSA ARM devices
 */

/*
 * USB devices
 */
#define CONFIG_SND_USB_AUDIO_MODULE 1

/*
 * PCMCIA devices
 */

/*
 * Open Sound System
 */
#undef CONFIG_SOUND_PRIME

/*
 * USB support
 */
#define CONFIG_USB_ARCH_HAS_HCD 1
#undef CONFIG_USB_ARCH_HAS_OHCI
#define CONFIG_USB 1
#undef CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#undef CONFIG_USB_DEVICEFS
#undef CONFIG_USB_BANDWIDTH
#undef CONFIG_USB_DYNAMIC_MINORS
#define CONFIG_USB_SUSPEND 1
#undef CONFIG_USB_OTG

/*
 * USB Host Controller Drivers
 */
#define CONFIG_USB_SL811_HCD_MODULE 1
#define CONFIG_USB_SL811_CS_MODULE 1

/*
 * USB Device Class drivers
 */
#define CONFIG_USB_AUDIO_MODULE 1

/*
 * USB Bluetooth TTY can only be used with disabled Bluetooth subsystem
 */
#undef CONFIG_USB_MIDI
#define CONFIG_USB_ACM_MODULE 1
#define CONFIG_USB_PRINTER_MODULE 1

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support' may also be needed; see USB_STORAGE Help for more information
 */
#define CONFIG_USB_STORAGE_MODULE 1
#undef CONFIG_USB_STORAGE_DEBUG
#undef CONFIG_USB_STORAGE_DATAFAB
#undef CONFIG_USB_STORAGE_FREECOM
#undef CONFIG_USB_STORAGE_DPCM
#undef CONFIG_USB_STORAGE_USBAT
#undef CONFIG_USB_STORAGE_SDDR09
#undef CONFIG_USB_STORAGE_SDDR55
#undef CONFIG_USB_STORAGE_JUMPSHOT

/*
 * USB Input Devices
 */
#define CONFIG_USB_HID_MODULE 1
#define CONFIG_USB_HIDINPUT 1
#undef CONFIG_HID_FF
#define CONFIG_USB_HIDDEV 1

/*
 * USB HID Boot Protocol drivers
 */
#define CONFIG_USB_KBD_MODULE 1
#define CONFIG_USB_MOUSE_MODULE 1
#undef CONFIG_USB_AIPTEK
#undef CONFIG_USB_WACOM
#undef CONFIG_USB_KBTAB
#undef CONFIG_USB_POWERMATE
#undef CONFIG_USB_MTOUCH
#undef CONFIG_USB_EGALAX
#undef CONFIG_USB_XPAD
#undef CONFIG_USB_ATI_REMOTE

/*
 * USB Imaging devices
 */
#define CONFIG_USB_MDC800_MODULE 1
#define CONFIG_USB_MICROTEK_MODULE 1

/*
 * USB Multimedia devices
 */
#undef CONFIG_USB_DABUSB
#undef CONFIG_USB_VICAM
#define CONFIG_USB_DSBR_MODULE 1
#undef CONFIG_USB_IBMCAM
#undef CONFIG_USB_KONICAWC
#undef CONFIG_USB_OV511
#undef CONFIG_USB_SE401
#define CONFIG_USB_SN9C102_MODULE 1
#undef CONFIG_USB_STV680
#define CONFIG_USB_PWC_MODULE 1

/*
 * USB Network Adapters
 */
#define CONFIG_USB_CATC_MODULE 1
#define CONFIG_USB_KAWETH_MODULE 1
#define CONFIG_USB_PEGASUS_MODULE 1
#define CONFIG_USB_RTL8150_MODULE 1
#define CONFIG_USB_USBNET_MODULE 1

/*
 * USB Host-to-Host Cables
 */
#define CONFIG_USB_ALI_M5632 1
#define CONFIG_USB_AN2720 1
#define CONFIG_USB_BELKIN 1
#define CONFIG_USB_GENESYS 1
#define CONFIG_USB_NET1080 1
#define CONFIG_USB_PL2301 1
#define CONFIG_USB_KC2190 1

/*
 * Intelligent USB Devices/Gadgets
 */
#define CONFIG_USB_ARMLINUX 1
#define CONFIG_USB_EPSON2888 1
#define CONFIG_USB_ZAURUS 1
#define CONFIG_USB_CDCETHER 1

/*
 * USB Network Adapters
 */
#define CONFIG_USB_AX8817X 1
#define CONFIG_USB_ZD1201_MODULE 1
#define CONFIG_USB_MON 1

/*
 * USB port drivers
 */
#define CONFIG_USB_USS720_MODULE 1

/*
 * USB Serial Converter support
 */
#define CONFIG_USB_SERIAL_MODULE 1
#define CONFIG_USB_SERIAL_GENERIC 1
#undef CONFIG_USB_SERIAL_AIRPRIME
#define CONFIG_USB_SERIAL_BELKIN_MODULE 1
#define CONFIG_USB_SERIAL_DIGI_ACCELEPORT_MODULE 1
#undef CONFIG_USB_SERIAL_CP2101
#define CONFIG_USB_SERIAL_CYPRESS_M8_MODULE 1
#define CONFIG_USB_SERIAL_EMPEG_MODULE 1
#define CONFIG_USB_SERIAL_FTDI_SIO_MODULE 1
#define CONFIG_USB_SERIAL_VISOR_MODULE 1
#define CONFIG_USB_SERIAL_IPAQ_MODULE 1
#define CONFIG_USB_SERIAL_IR_MODULE 1
#define CONFIG_USB_SERIAL_EDGEPORT_MODULE 1
#define CONFIG_USB_SERIAL_EDGEPORT_TI_MODULE 1
#define CONFIG_USB_SERIAL_GARMIN_MODULE 1
#define CONFIG_USB_SERIAL_IPW_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_PDA_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_MPR 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28X 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28XA 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28XB 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA18X 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19W 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QW 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QI 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA49W 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA49WLC 1
#define CONFIG_USB_SERIAL_KLSI_MODULE 1
#define CONFIG_USB_SERIAL_KOBIL_SCT_MODULE 1
#define CONFIG_USB_SERIAL_MCT_U232_MODULE 1
#define CONFIG_USB_SERIAL_PL2303_MODULE 1
#define CONFIG_USB_SERIAL_HP4X_MODULE 1
#define CONFIG_USB_SERIAL_SAFE_MODULE 1
#undef CONFIG_USB_SERIAL_SAFE_PADDED
#define CONFIG_USB_SERIAL_TI_MODULE 1
#define CONFIG_USB_SERIAL_CYBERJACK_MODULE 1
#define CONFIG_USB_SERIAL_XIRCOM_MODULE 1
#define CONFIG_USB_SERIAL_OMNINET_MODULE 1
#define CONFIG_USB_EZUSB 1

/*
 * USB Miscellaneous drivers
 */
#define CONFIG_USB_EMI62_MODULE 1
#define CONFIG_USB_EMI26_MODULE 1
#undef CONFIG_USB_AUERSWALD
#define CONFIG_USB_RIO500_MODULE 1
#define CONFIG_USB_LEGOTOWER_MODULE 1
#define CONFIG_USB_LCD_MODULE 1
#define CONFIG_USB_LED_MODULE 1
#define CONFIG_USB_CYTHERM_MODULE 1
#undef CONFIG_USB_PHIDGETKIT
#undef CONFIG_USB_PHIDGETSERVO
#define CONFIG_USB_IDMOUSE_MODULE 1

/*
 * USB ATM/DSL drivers
 */
#define CONFIG_USB_ATM_MODULE 1
#define CONFIG_USB_SPEEDTOUCH_MODULE 1

/*
 * USB Gadget Support
 */
#define CONFIG_USB_GADGET_MODULE 1
#undef CONFIG_USB_GADGET_DEBUG_FILES
#undef CONFIG_USB_GADGET_NET2280
#undef CONFIG_USB_GADGET_PXA2XX
#undef CONFIG_USB_GADGET_GOKU
#undef CONFIG_USB_GADGET_LH7A40X
#undef CONFIG_USB_GADGET_OMAP
#undef CONFIG_MV88f5181_USB_GADGET_DUMMY
#define CONFIG_USB_GADGET_DUMMY_HCD 1
#define CONFIG_USB_DUMMY_HCD_MODULE 1
#define CONFIG_USB_GADGET_DUALSPEED 1
#define CONFIG_USB_ZERO_MODULE 1
#define CONFIG_USB_ETH_MODULE 1
#define CONFIG_USB_ETH_RNDIS 1
#define CONFIG_USB_GADGETFS_MODULE 1
#define CONFIG_USB_FILE_STORAGE_MODULE 1
#undef CONFIG_USB_FILE_STORAGE_TEST
#define CONFIG_USB_G_SERIAL_MODULE 1

/*
 * MMC/SD Card support
 */
#define CONFIG_MMC 1
#undef CONFIG_MMC_DEBUG
#define CONFIG_MMC_BLOCK_MODULE 1
#define CONFIG_MMC_WBSD_MODULE 1

/*
 * File systems
 */
#define CONFIG_EXT2_FS 1
#define CONFIG_EXT2_FS_XATTR 1
#define CONFIG_EXT2_FS_POSIX_ACL 1
#define CONFIG_EXT2_FS_SECURITY 1
#define CONFIG_EXT3_FS 1
#define CONFIG_EXT3_FS_XATTR 1
#define CONFIG_EXT3_FS_POSIX_ACL 1
#define CONFIG_EXT3_FS_SECURITY 1
#define CONFIG_JBD 1
#undef CONFIG_JBD_DEBUG
#define CONFIG_FS_MBCACHE 1
#define CONFIG_REISERFS_FS_MODULE 1
#undef CONFIG_REISERFS_CHECK
#undef CONFIG_REISERFS_PROC_INFO
#define CONFIG_REISERFS_FS_XATTR 1
#define CONFIG_REISERFS_FS_POSIX_ACL 1
#define CONFIG_REISERFS_FS_SECURITY 1
#define CONFIG_JFS_FS_MODULE 1
#define CONFIG_JFS_POSIX_ACL 1
#define CONFIG_JFS_SECURITY 1
#undef CONFIG_JFS_DEBUG
#define CONFIG_JFS_STATISTICS 1
#define CONFIG_FS_POSIX_ACL 1

/*
 * XFS support
 */
#define CONFIG_XFS_FS_MODULE 1
#define CONFIG_XFS_EXPORT 1
#define CONFIG_XFS_RT 1
#define CONFIG_XFS_QUOTA 1
#undef CONFIG_XFS_SECURITY
#define CONFIG_XFS_POSIX_ACL 1
#define CONFIG_MINIX_FS_MODULE 1
#define CONFIG_ROMFS_FS_MODULE 1
#define CONFIG_INOTIFY 1
#define CONFIG_QUOTA 1
#define CONFIG_QFMT_V1_MODULE 1
#define CONFIG_QFMT_V2_MODULE 1
#define CONFIG_QUOTACTL 1
#define CONFIG_DNOTIFY 1
#undef CONFIG_AUTOFS_FS
#define CONFIG_AUTOFS4_FS_MODULE 1

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS_MODULE 1
#define CONFIG_JOLIET 1
#define CONFIG_ZISOFS 1
#define CONFIG_ZISOFS_FS_MODULE 1
#define CONFIG_UDF_FS_MODULE 1
#define CONFIG_UDF_NLS 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS_MODULE 1
#define CONFIG_MSDOS_FS_MODULE 1
#define CONFIG_VFAT_FS_MODULE 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#define CONFIG_NTFS_FS_MODULE 1
#undef CONFIG_NTFS_DEBUG
#undef CONFIG_NTFS_RW

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_SYSFS 1
#undef CONFIG_DEVFS_FS
#undef CONFIG_DEVPTS_FS_XATTR
#define CONFIG_TMPFS 1
#define CONFIG_TMPFS_XATTR 1
#undef CONFIG_TMPFS_SECURITY
#undef CONFIG_HUGETLB_PAGE
#define CONFIG_RAMFS 1

/*
 * Miscellaneous filesystems
 */
#define CONFIG_ADFS_FS_MODULE 1
#undef CONFIG_ADFS_FS_RW
#define CONFIG_AFFS_FS_MODULE 1
#define CONFIG_HFS_FS_MODULE 1
#define CONFIG_HFSPLUS_FS_MODULE 1
#define CONFIG_BEFS_FS_MODULE 1
#undef CONFIG_BEFS_DEBUG
#define CONFIG_BFS_FS_MODULE 1
#define CONFIG_EFS_FS_MODULE 1
#undef CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS_MODULE 1
#define CONFIG_JFFS2_FS_DEBUG 0
#undef CONFIG_JFFS2_FS_NAND
#undef CONFIG_JFFS2_FS_NOR_ECC
#define CONFIG_JFFS2_COMPRESSION_OPTIONS 1
#define CONFIG_JFFS2_ZLIB 1
#define CONFIG_JFFS2_RTIME 1
#undef CONFIG_JFFS2_RUBIN
#undef CONFIG_JFFS2_CMODE_NONE
#define CONFIG_JFFS2_CMODE_PRIORITY 1
#undef CONFIG_JFFS2_CMODE_SIZE
#define CONFIG_CRAMFS_MODULE 1
#define CONFIG_SQUASHFS_MODULE 1
#undef CONFIG_SQUASHFS_EMBEDDED
#define CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE 3
#define CONFIG_VXFS_FS_MODULE 1
#define CONFIG_HPFS_FS_MODULE 1
#define CONFIG_QNX4FS_FS_MODULE 1
#define CONFIG_SYSV_FS_MODULE 1
#define CONFIG_UFS_FS_MODULE 1
#undef CONFIG_UFS_FS_WRITE

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS_MODULE 1
#define CONFIG_NFS_V3 1
#define CONFIG_NFS_V4 1
#undef CONFIG_NFS_DIRECTIO
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V3 1
#define CONFIG_NFSD_V4 1
#define CONFIG_NFSD_TCP 1
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_EXPORTFS_MODULE 1
#define CONFIG_SUNRPC_MODULE 1
#define CONFIG_SUNRPC_GSS_MODULE 1
#define CONFIG_RPCSEC_GSS_KRB5_MODULE 1
#undef CONFIG_RPCSEC_GSS_SPKM3
#undef CONFIG_SMB_FS
#define CONFIG_CIFS_MODULE 1
#undef CONFIG_CIFS_STATS
#define CONFIG_CIFS_XATTR 1
#define CONFIG_CIFS_POSIX 1
#undef CONFIG_CIFS_EXPERIMENTAL
#define CONFIG_NCP_FS_MODULE 1
#define CONFIG_NCPFS_PACKET_SIGNING 1
#define CONFIG_NCPFS_IOCTL_LOCKING 1
#define CONFIG_NCPFS_STRONG 1
#define CONFIG_NCPFS_NFS_NS 1
#define CONFIG_NCPFS_OS2_NS 1
#undef CONFIG_NCPFS_SMALLDOS
#define CONFIG_NCPFS_NLS 1
#define CONFIG_NCPFS_EXTRAS 1
#define CONFIG_CODA_FS_MODULE 1
#undef CONFIG_CODA_FS_OLD_API
#define CONFIG_AFS_FS_MODULE 1
#define CONFIG_RXRPC_MODULE 1

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#define CONFIG_ACORN_PARTITION 1
#undef CONFIG_ACORN_PARTITION_CUMANA
#undef CONFIG_ACORN_PARTITION_EESOX
#define CONFIG_ACORN_PARTITION_ICS 1
#undef CONFIG_ACORN_PARTITION_ADFS
#undef CONFIG_ACORN_PARTITION_POWERTEC
#define CONFIG_ACORN_PARTITION_RISCIX 1
#define CONFIG_OSF_PARTITION 1
#define CONFIG_AMIGA_PARTITION 1
#define CONFIG_ATARI_PARTITION 1
#define CONFIG_MAC_PARTITION 1
#define CONFIG_MSDOS_PARTITION 1
#define CONFIG_BSD_DISKLABEL 1
#define CONFIG_MINIX_SUBPARTITION 1
#define CONFIG_SOLARIS_X86_PARTITION 1
#define CONFIG_UNIXWARE_DISKLABEL 1
#define CONFIG_LDM_PARTITION 1
#undef CONFIG_LDM_DEBUG
#define CONFIG_SGI_PARTITION 1
#define CONFIG_ULTRIX_PARTITION 1
#define CONFIG_SUN_PARTITION 1
#define CONFIG_EFI_PARTITION 1

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "utf8"
#define CONFIG_NLS_CODEPAGE_437_MODULE 1
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#define CONFIG_NLS_CODEPAGE_936_MODULE 1
#define CONFIG_NLS_CODEPAGE_950_MODULE 1
#define CONFIG_NLS_CODEPAGE_932_MODULE 1
#define CONFIG_NLS_CODEPAGE_949_MODULE 1
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#define CONFIG_NLS_ISO8859_8_MODULE 1
#define CONFIG_NLS_CODEPAGE_1250_MODULE 1
#define CONFIG_NLS_CODEPAGE_1251_MODULE 1
#define CONFIG_NLS_ASCII_MODULE 1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#define CONFIG_NLS_ISO8859_2_MODULE 1
#define CONFIG_NLS_ISO8859_3_MODULE 1
#define CONFIG_NLS_ISO8859_4_MODULE 1
#define CONFIG_NLS_ISO8859_5_MODULE 1
#define CONFIG_NLS_ISO8859_6_MODULE 1
#define CONFIG_NLS_ISO8859_7_MODULE 1
#define CONFIG_NLS_ISO8859_9_MODULE 1
#define CONFIG_NLS_ISO8859_13_MODULE 1
#define CONFIG_NLS_ISO8859_14_MODULE 1
#define CONFIG_NLS_ISO8859_15_MODULE 1
#define CONFIG_NLS_KOI8_R_MODULE 1
#define CONFIG_NLS_KOI8_U_MODULE 1
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Profiling support
 */
#define CONFIG_PROFILING 1
#define CONFIG_OPROFILE_MODULE 1

/*
 * Kernel hacking
 */
#define CONFIG_PRINTK_TIME 1
#define CONFIG_DEBUG_KERNEL 1
#define CONFIG_MAGIC_SYSRQ 1
#define CONFIG_LOG_BUF_SHIFT 18
#define CONFIG_SCHEDSTATS 1
#undef CONFIG_DEBUG_SLAB
#undef CONFIG_DEBUG_SPINLOCK
#undef CONFIG_DEBUG_SPINLOCK_SLEEP
#undef CONFIG_DEBUG_KOBJECT
#define CONFIG_DEBUG_BUGVERBOSE 1
#define CONFIG_DEBUG_INFO 1
#define CONFIG_DEBUG_FS 1
#define CONFIG_FRAME_POINTER 1
#undef CONFIG_DEBUG_USER
#undef CONFIG_DEBUG_WAITQ
#undef CONFIG_DEBUG_ERRORS
#undef CONFIG_DEBUG_LL

/*
 * Security options
 */
#define CONFIG_KEYS 1
#undef CONFIG_KEYS_DEBUG_PROC_KEYS
#define CONFIG_SECURITY 1
#define CONFIG_SECURITY_NETWORK 1
#undef CONFIG_SECURITY_CAPABILITIES
#undef CONFIG_SECURITY_ROOTPLUG
#undef CONFIG_SECURITY_SECLVL
#define CONFIG_SECURITY_SELINUX 1
#define CONFIG_SECURITY_SELINUX_BOOTPARAM 1
#define CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE 0
#define CONFIG_SECURITY_SELINUX_DISABLE 1
#define CONFIG_SECURITY_SELINUX_DEVELOP 1
#define CONFIG_SECURITY_SELINUX_AVC_STATS 1
#define CONFIG_SECURITY_SELINUX_CHECKREQPROT_VALUE 1

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#define CONFIG_CRYPTO_NULL_MODULE 1
#define CONFIG_CRYPTO_MD4_MODULE 1
#define CONFIG_CRYPTO_MD5 1
#define CONFIG_CRYPTO_SHA1 1
#define CONFIG_CRYPTO_SHA256 1
#define CONFIG_CRYPTO_SHA512_MODULE 1
#define CONFIG_CRYPTO_WP512_MODULE 1
#define CONFIG_CRYPTO_TGR192_MODULE 1
#define CONFIG_CRYPTO_DES_MODULE 1
#define CONFIG_CRYPTO_BLOWFISH_MODULE 1
#define CONFIG_CRYPTO_TWOFISH_MODULE 1
#define CONFIG_CRYPTO_SERPENT_MODULE 1
#define CONFIG_CRYPTO_AES 1
#define CONFIG_CRYPTO_CAST5_MODULE 1
#define CONFIG_CRYPTO_CAST6_MODULE 1
#define CONFIG_CRYPTO_TEA_MODULE 1
#define CONFIG_CRYPTO_ARC4_MODULE 1
#define CONFIG_CRYPTO_KHAZAD_MODULE 1
#define CONFIG_CRYPTO_ANUBIS_MODULE 1
#define CONFIG_CRYPTO_DEFLATE_MODULE 1
#define CONFIG_CRYPTO_MICHAEL_MIC_MODULE 1
#define CONFIG_CRYPTO_CRC32C 1
#define CONFIG_CRYPTO_TEST_MODULE 1

/*
 * OCF Configuration
 */
#undef CONFIG_OCF_OCF

/*
 * Hardware crypto devices
 */

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT_MODULE 1
#define CONFIG_CRC32 1
#define CONFIG_LIBCRC32C 1
#define CONFIG_ZLIB_INFLATE_MODULE 1
#define CONFIG_ZLIB_DEFLATE_MODULE 1
#define CONFIG_REED_SOLOMON_MODULE 1
#define CONFIG_REED_SOLOMON_DEC16 1
